# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: savesync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'savesync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esavesync.proto\x12\x0cgamesavesync\"3\n\x05saves\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04save\x18\x03 \x01(\x0c\"5\n\x0c\x45stadoSubida\x12\x14\n\x0c\x63onfirmacion\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0c\x45stadoBajada\x12\x0c\n\x04save\x18\x01 \x01(\x0c\"#\n\x15PeticionBajarGuardado\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xa6\x01\n\x10TrabajarGuardado\x12?\n\nUploadSave\x12\x13.gamesavesync.saves\x1a\x1a.gamesavesync.EstadoSubida(\x01\x12Q\n\x0c\x44ownloadSave\x12#.gamesavesync.PeticionBajarGuardado\x1a\x1a.gamesavesync.EstadoBajada0\x01\x42\x16\xaa\x02\x13GameSaveSync.Serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'savesync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023GameSaveSync.Server'
  _globals['_SAVES']._serialized_start=32
  _globals['_SAVES']._serialized_end=83
  _globals['_ESTADOSUBIDA']._serialized_start=85
  _globals['_ESTADOSUBIDA']._serialized_end=138
  _globals['_ESTADOBAJADA']._serialized_start=140
  _globals['_ESTADOBAJADA']._serialized_end=168
  _globals['_PETICIONBAJARGUARDADO']._serialized_start=170
  _globals['_PETICIONBAJARGUARDADO']._serialized_end=205
  _globals['_TRABAJARGUARDADO']._serialized_start=208
  _globals['_TRABAJARGUARDADO']._serialized_end=374
# @@protoc_insertion_point(module_scope)
