# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import savesync_pb2 as savesync__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in savesync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrabajarGuardadoStub(object):
    """defino el servicio de pillar el guardado tanto para serializarlo a la hora de llegar del cliente como deserializarlo a la hora de mandarlo a otro cliente

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadSave = channel.stream_unary(
                '/gamesavesync.TrabajarGuardado/UploadSave',
                request_serializer=savesync__pb2.saves.SerializeToString,
                response_deserializer=savesync__pb2.EstadoSubida.FromString,
                _registered_method=True)
        self.DownloadSave = channel.unary_stream(
                '/gamesavesync.TrabajarGuardado/DownloadSave',
                request_serializer=savesync__pb2.PeticionBajarGuardado.SerializeToString,
                response_deserializer=savesync__pb2.EstadoBajada.FromString,
                _registered_method=True)


class TrabajarGuardadoServicer(object):
    """defino el servicio de pillar el guardado tanto para serializarlo a la hora de llegar del cliente como deserializarlo a la hora de mandarlo a otro cliente

    """

    def UploadSave(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadSave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrabajarGuardadoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadSave': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadSave,
                    request_deserializer=savesync__pb2.saves.FromString,
                    response_serializer=savesync__pb2.EstadoSubida.SerializeToString,
            ),
            'DownloadSave': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadSave,
                    request_deserializer=savesync__pb2.PeticionBajarGuardado.FromString,
                    response_serializer=savesync__pb2.EstadoBajada.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gamesavesync.TrabajarGuardado', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gamesavesync.TrabajarGuardado', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrabajarGuardado(object):
    """defino el servicio de pillar el guardado tanto para serializarlo a la hora de llegar del cliente como deserializarlo a la hora de mandarlo a otro cliente

    """

    @staticmethod
    def UploadSave(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gamesavesync.TrabajarGuardado/UploadSave',
            savesync__pb2.saves.SerializeToString,
            savesync__pb2.EstadoSubida.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadSave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gamesavesync.TrabajarGuardado/DownloadSave',
            savesync__pb2.PeticionBajarGuardado.SerializeToString,
            savesync__pb2.EstadoBajada.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
